export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_DOCTORS = 'FETCH_DOCTORS';
export const FETCH_DOCTORS_REJECTED = 'FETCH_DOCTORS_REJECTED';
export const FETCH_DOCTORS_FULFILLED = 'FETCH_DOCTORS_FULFILLED';
export const SELECTED_DOCTOR = 'SELECTED_DOCTOR';
