export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const FETCH_DOCTORS = 'FETCH_DOCTORS';
export const FETCH_DOCTORS_REJECTED = 'FETCH_DOCTORS_REJECTED';
export const FETCH_DOCTORS_FULFILLED = 'FETCH_DOCTORS_FULFILLED';

export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_REJECTED = 'USER_SIGNUP_REJECTED';
export const USER_SIGNUP_FULFILLED = 'USER_SIGNUP_FULFILLED';

export const VALIDATE_USER = 'VALIDATE_USER';
export const VALIDATE_USER_REJECTED = 'VALIDATE_USER_REJECTED';
export const VALIDATE_USER_FULFILLED = 'USER_FULFILLED';
export const RESET_VALIDATE_USER = 'RESET_VALIDATE_USER';

export const SET_USER_GEO_LOCATION = 'SET_USER_GEO_LOCATION';
